name: Hibernate OGM Cassandra CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
    branches: master

jobs:
  build:
    name: Build the project and run the tests
    runs-on: ubuntu-latest
    services:
       # Label used to access the service container
      cassandra:
        # Docker Hub image
        image: cassandra:3.7
          #        options: >-
          #--health-cmd="mysqladmin ping"
          #--health-interval 10s
          #--health-timeout 5s
          #--health-retries 5
        ports:
          - 9042:9042
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      with:
        java-version: 1.8
      uses: actions/setup-java@v1
    - name: Build with Maven
      run: mvn clean install -s settings-example.xml

